### ISSUE TITLE
platform/windows: No output, only `html/static/js/search-index.js`

### ISSUE THREAD

**Issue by ryanabx** [irskep/djockey#42]
Hi, I finally got a chance to try out Djockey, and unfortunately it didn't work on the first go :/

My config file is:

```yaml
input_dir: src
output_dir:
  html: docs-out/html
  gfm: docs-out/gfm
site_name: "Ryan's Documentation"
url_root: .

html:
  footer_text: "Ryan Brue 2024"
```

and my directory tree is:

```
C:\USERS\RYAN.BRUE\DOCUMENTS\DOCUMENTATION\DOCS
│   djockey.yaml
│
└───src
    │   index.dj
    │
    ├───daily_docs
    │   │   202406.dj
    │   │   202407.dj
    │   │   202408.dj
    │   │   202409.dj
    │   │   index.dj
    │   │
    │   └───resources
    │       ├───202406
    │       │       image-1.png
    │       │       image-2.png
    │       │       image.png
    │       │
    │       ├───202407
    │       │       image.png
    │       │
    │       └───202408
    │               image.png
    │               image2.png
    │
    └───notes
            20240829_meeting.dj
            20240830.dj
            ci_idea.dj
            index.dj
```

I ran `npx djockey docs` and all I got is this in my project root directory:

```
C:\USERS\RYAN.BRUE\DOCUMENTS\DOCUMENTATION\DOCS-OUT
└───html
    └───static
        └───js
                search-index.js
```

Looking forward to getting it to work, I'm not sure what I ended up doing wrong!

PS if it helps, the program output didn't spout out any error either:

```
√ Parsing documents
√ Setting up plugins
√ Transform pass 1 of 1
√ Connecting pages
√ Copying static files
√ Rendering html
```
